version: "3"
services:
  nginx3:
    container_name: "nginx3"
    image: "nginx:1.17.9"
    ports:
      - "8080:80"
    links:
      - "php3"
    volumes:
      - ./html:/var/www/html/
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
  php3:
    container_name: "php3"
    image: "php:7.4-fpm"
    ports:
      - "9000:9000"
    volumes:
      - ./html:/var/www/html/
    links:
      - "mysql3"
  mysql3:
    container_name: "mysql3"
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD : 123456
